openapi: 3.0.0
info:
  title: Comparator
  description: Comparator
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /authorizations:
    description: TODO resource schema
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Authorization"
      responses:
        200:
          description: Authorization created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorization"
  /compare:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Comparison"
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                properties:
                  result:
                    type: boolean
components:
  schemas:
    Authorization:
      description: An authorization.
      type: object
      required:
        - scope
        - requestingParties
      properties:
        id:
          type: string
        scope:
          type: array
          items:
            $ref: "#/components/schemas/Scope"
        requestingParty:
          description: keyID
          type: string
    Scope:
      type: object
      required:
        - vaultID
        - docID
      properties:
        vaultID:
          type: string
        docID:
          type: string
        caveats:
          type: array
          items:
            $ref: "#/components/schemas/Caveat"
    Caveat:
      type: object
      properties:
        type:
          type: string
          enum:
            - expiry
    ExpiryCaveat:
      allOf:
        - $ref: "#/components/schemas/Caveat"
        - type: object
          properties:
            duration:
              type: integer
              description: Duration (in seconds) for which this authorization will remain valid.
    Comparison:
      type: object
      properties:
        op:
          $ref: "#/components/schemas/Operator"
    Operator:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - eq
    EqOp:
      allOf:
        - $ref: "#/components/schemas/Operator"
        - type: object
          required:
            - args
          properties:
            args:
              type: array
              items:
                $ref: "#/components/schemas/Query"
              minItems: 2
    Query:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - doc
            - ref
    DocQuery:
      allOf:
        - $ref: "#/components/schemas/Query"
        - type: object
          required:
            - vaultID
            - docID
          properties:
            vaultID:
              type: string
            docID:
              type: string
    RefQuery:
      allOf:
        - $ref: "#/components/schemas/Query"
        - type: object
          required:
            - ref
          properties:
            ref:
              type: string
            zcap:
              type: object
