openapi: 3.0.0
info:
  title: Membership Service
  description: Membership Service
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /membership:
    get:
      responses:
        200:
          description: Token membership.
          content:
            application/ld+json:
              schema:
                type: object
            text/plain:
              schema:
                type: string
  /describe:
    post:
      requestBody:
        description: Describe the membership object.
        content:
          application/ld+json:
            schema:
              type: object
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: Membership metadata.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MembershipMetadata"
components:
  schemas:
    MembershipMetadata:
      type: object
      properties:
        domain:
          type: string
        did:
          type: string
