openapi: 3.0.0
info:
  title: Vault API
  description: Vault API
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /vaults:
    post:
      description: Creates a new vault.
      responses:
        201:
          description: Vault created successfully.
          headers:
            Location:
              description: Location of the vault
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vault"
  /vaults/{vaultID}/docs:
    post:
      description: Encrypts and stores the document in the vault.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Document"
      responses:
        201:
          description: Document encrypted and stored successfully.
          headers:
            Location:
              description: Location of the document's metadata.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentMetadata"
  /vaults/{vaultID}/docs/{docID}/metadata:
    get:
      description: The plaintext document.
      responses:
        200:
          description: The plaintext document.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentMetadata"
  /vaults/{vaultID}/authorizations:
    post:
      description: Create an authorization.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Authorization"
      responses:
        201:
          description: Authorization created.
          headers:
            Location:
              description: Location of the authorization
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorization"
  /vaults/{vaultID}/authorizations/{authorizationID}:
    get:
      description: Fetch an authorization.
      responses:
        200:
          description: An authorization object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorization"
    delete:
      description: Delete an authorization.
      responses:
        200:
          description: Authorization deleted.
components:
  schemas:
    Vault:
      type: object
      required:
      properties:
        id:
          type: string
          description: Unique identifier for the vault.
        edv:
          type: object
          properties:
            uri:
              type: string
            zcap:
              type: string
        kms:
          type: object
          properties:
            uri:
              type: string
            zcap:
              type: string
    Document:
      type: object
      properties:
        content:
          description: The document to be encrypted and stored in the vault.
          type: object
    DocumentMetadata:
      type: object
      properties:
        docID:
          type: string
        edvDocURI:
          type: string
    Authorization:
      description: An authorization.
      type: object
      required:
        - scope
        - requestingParties
      properties:
        id:
          type: string
        scope:
          $ref: "#/components/schemas/Scope"
        requestingParty:
          description: keyID
          type: string
        edv:
          type: object
          properties:
            url:
              type: string
            zcap:
              description: a base64url-encoded zcap
              type: string
        kms:
          type: object
          properties:
            url:
              type: string
            zcap:
              description: a base64url-encoded zcap
              type: string
    Scope:
      type: object
      required:
        - target
        - actions
      properties:
        target:
          type: string
        targetAttr:
          type: string
        actions:
          type: array
          items:
            type: string
        caveats:
          type: array
          items:
            $ref: "#/components/schemas/Caveat"
    Caveat:
      type: object
      properties:
        type:
          type: string
          enum:
            - expiry
    ExpiryCaveat:
      allOf:
        - $ref: "#/components/schemas/Caveat"
        - type: object
          properties:
            duration:
              type: integer
              description: Duration (in seconds) for which this authorization will remain valid.
