@startuml

title Payroll Flow

actor "Account Holder" as user

box Client Domain 1 #LightBlue
  participant APP as d1
  participant "Vault API" as vapi1
  participant Comparator as comp1
  participant "VC HTTP API" as vcrest1
  participant Proxy as proxy1
end box

box Client Domain 2 #LightBlue
  participant APP as d2
  participant "Vault API" as vapi2
  participant Comparator as comp2
  participant "VC HTTP API" as vcrest2
  participant Proxy as proxy2
end box

box Common Hosted Services #LightRed
  participant Gateway as gate
  participant "did:orb" as dlt
  participant "Confidential Storage Hub" as edx
  participant EDV as edv
  participant WebKMS as kms
end box

group prior one-time setup
  loop for each client domain
    gate -> gate : newOrgSecret()
    gate --> d1 : (out of band) orgSecret
    d1 --> proxy1 : (out of band) configure(orgSecret)
    comp1 -> comp1 : newKeyPair()
    comp1 -> proxy1 : createDID(pubKey)
    proxy1 -> gate : createDID(pubKey)
    gate -> dlt : createDID(pubKey)
    dlt -> gate : did:orb:svc
    gate -> proxy1 : did:orb:svc
    proxy1 -> comp1 : did:orb:svc
    comp1 -> proxy1: POST /hubstore/acct {controller=did:orb:svc#key}
    proxy1 -> gate : POST /hubstore/acct {controller=did:orb:svc#key}
    gate -> edx : POST /hubstore/acct {controller=did:orb:svc#key}
    edx -> dlt : resolve(did:orb:svc)
    dlt -> edx : did:orb:svc
    edx -> gate : accountID, orgCompZCAP
    gate -> proxy1 : accountID, orgCompZCAP
    proxy1 -> comp1 : accountID, orgCompZCAP
    d1 -> comp1 : getConfig()
    comp1 -> d1 : did:orb:svc, orgKeyPair
    d1 -> vcrest1 : createProfile(did:orb:svc, orgPrivKey)
    vcrest1 -> d1 : IssuerProfile
    d1 --> d2 : (oauth2 client registration) RFC7591 + did:orb:svc
  end
end

loop for each user registration at Client Domain
  user -> d1 : Registration w/SSN
  d1 -> vapi1 : POST /vaults
  vapi1 -> vapi1 : newVaultPrimaryKey()
  vapi1 -> dlt : createDID(vaultPubKey)
  dlt -> vapi1 : did:orb:vault
  vapi1 -> kms : POST /keystores {controller=did:orb:vault#key}
  kms -> vapi1 : keystoreID, vaultKMSZCAP
  vapi1 -> edv : POST /encrypted-data-vaults {controller=did:orb:vault#key}
  edv -> vapi1 : edvVaultID, vaultEDVZCAP
  vapi1 -> d1 : did:orb:vault
  note left: vault created: UniversalWallet profile
  d1 -> vcrest1 : POST /{id}/credentials/issueCredential {subj=did:orb:vault, ssn=abc123}
  vcrest1 -> d1 : vc
  note left: VC created containing SSN, with vaultDID as subject
  d1 -> vapi1 : POST /vaults/{vaultDID}/docs {id=did:orb:vault, content=vc}
  vapi1 -> vapi1 : let CEK = newCEK()
  vapi1 -> vapi1 : let encryptedVC = encrypt(CEK, vc)
  vapi1 -> kms : POST /keystores/{keystoreID}/keys authz=HTTPSIG(vaultKMSZCAP)
  kms -> vapi1 : keyID
  vapi1 -> kms : POST /keystores/{keystoreID}/wrap {CEK, recipient=keyID} authz=HTTPSIG(vaultKMSZCAP)
  kms -> vapi1 : wrappedCEK
  vapi1 -> vapi1 : newEDVEncryptedDoc(id=did:orb:vault, encryptedVC, wrappedCEK)
  note left: TODO map did:orb into an EDV document ID
  vapi1 -> edv : POST /encrypted-data-vaults/{vaultID}/documents {encryptedDoc} authz=HTTPSIG(vaultEDVZCAP)
  edv -> vapi1 : edvDocURI
  vapi1 -> d1 : OK
  note left: SSN VC encrypted and stored
end

group a client requests authorization to read another client's list of documents
  d1 -> d2 : please send employee list who are eligible for payroll
  d2 -> d2 : let authZList = newList()
  loop for each did:orb:vault in d2
    d2 -> vapi2 : POST /vaults/{vaultID}/authorizations {rp=hubPubDID, scope=["read", did:orb:vault, exp=5min]}
    vapi2 -> d2 : hubEDVZCAP, hubKMSZCAP
    d2 -> comp2 : POST /authorizations {rp=did:orb:svc1, scope=["read", did:orb:vault, exp=1day], authz=[hubEDVZCAP, hubKMSZCAP]}
    note left: OAuth2 client registration included their public DID
    comp2 -> vapi2 : GET /vaults/{vaultID}/docs/{docID}/metadata
    vapi2 -> comp2 : edvDocURI
    comp2 -> edx : POST /hubstore/acct/{accountID}/queries {edvDocURI, hubEDVZCAP, hubKMSZCAP} authz=HTTPSIG(orgCompZCAP)
    edx -> comp2 : queryID
    comp2 -> edx : POST /hubstore/acct/{accountID}/authorizations {rp=did:orb:svc1, scope=[queryID, "read", exp=1day]} authz=HTTPSIG(orgCompZCAP)
    edx -> comp2 : orgCompQueryZCAP
    comp2 -> d2 : orgCompQueryZCAP
    d2 -> d2 : authZList.append(orgCompQueryZCAP)
  end
  d2 -> d1 : authZList
  d1 -> comp1 : read(authZList)
  comp1 -> comp1 : let docList = newList()
  loop for each zcap in authZList
    comp1 -> comp1 : let orgCompQueryZCAP = authZList.pop()
    comp1 -> edx : GET /documents?ref=queryID authz=HTTPSIG(orgCompQueryZCAP)
    note left: comparator extracts queryID from orgCompQueryZCAP
    edx -> edx : lookup Query+Auth Objects by handle
    edx -> edv : readDoc(QueryObject, authz=HTTPSIG(hubEDVZCAP))
    edv -> edx : encryptedDoc
    edx -> kms : unwrap(wrappedCEK, authz=HTTPSIG(hubKMSZCAP))
    kms -> edx : unwrappedCEK
    edx -> edx : let doc = decrypt(encryptedDoc, unwrappedCEK)
    alt if query object has path
      edx -> edx : doc = select(jsonPath, decryptedDoc)
    end
    edx -> comp1 : doc
    comp1 -> comp1 : docList.append(doc)
  end
  comp1 -> d1 : docList
end

@enduml
