@startuml

box "Client Domain"
  actor "Relying Party" as rp
  participant "Vault API" as vapi
  participant Comparator as comp
end box

actor "Authorization Server" as as

rp -> as : OAuth2 request
as -> rp : OAuth2 code
rp -> as : code
as -> rp : access_token_as
rp -> vapi : authorize comparator to read a document in a vault
vapi -> rp : access_token_rp
rp -> comp : do comparison (access_token_as, access_token_rp)
comp -> rp : comparison result (true or false)

@enduml
