@startuml

actor "Relying Party" as rp

box "Authorization Server Domain"
  actor "Authorization Server" as as
  participant "Vault API" as vapi
  participant Comparator as comp
end box

rp -> as : OAuth2 request
as -> vapi : authorize comparator to read a document in a vault
as -> comp: authorize relying party to perform a comparison
comp -> as : access_token
as -> rp : OAuth2 code
rp -> as : code
as -> rp : access_token

@enduml
