@startuml

box "Client Domain"
  actor Client as client
  participant "Vault Server" as vaults
end box

client -> vaults : create vault
vaults -> client : UniversalWallet profile
client -> vaults : store document (docID, contents)

@enduml
